Optimise DBAdapter.getUnreadDirectsNumber to use indexes
FreeFeed/freefeed-server pull request #154
Opened 2016-11-26 17:55 UTC by davidmz

2016-11-27 17:36 UTC, indeyets requested changes

2016-11-27 17:36 UTC, indeyets commented on app/support/DbAdapter.js
> +          and created_at > ${pgQuote(directsReadAt)}
It's cleaner to use prepared-statements instead of `pgQuote`

2016-11-27 17:36 UTC, indeyets commented on app/support/DbAdapter.js
> +          destination_feed_ids && ARRAY[${directsFeedId}]
this looks like a case for `pgFormat('%L', [directsFeedId])`. no?

2016-11-28 17:08 UTC, davidmz commented
Included in #155

2016-11-28 17:08 UTC, closed without merging