[WIP] BestOf emails
FreeFeed/freefeed-server pull request #294
Opened 2018-03-13 16:11 UTC by golozubov

2018-04-01 17:55 UTC, davidmz commented on app/views/emails/best-of-digest/post-likes.jsx
> +      <a className="more-post-likes-link" href="#">{item.omittedLikes} other people</a>
Наверное, в письме не должно быть ссылок с href="#"? Стоит или совсем убрать ссылку или сделать полную ссылку на пост.

2018-04-01 17:56 UTC, davidmz commented on app/views/emails/best-of-digest/post-likes.jsx
> +      <i className="fa fa-heart icon"></i>
А к письму точно подключится иконочный шрифт?

2018-04-02 10:25 UTC, golozubov commented on app/views/emails/best-of-digest/post-likes.jsx
> +      <a className="more-post-likes-link" href="#">{item.omittedLikes} other people</a>
Да, скорее всего, там нужна ссылка на пост. Если, конечно, в финальном варианте письма будет вывод `omittedLikes`.

2018-04-02 10:27 UTC, golozubov commented on app/views/emails/best-of-digest/post-likes.jsx
> +      <i className="fa fa-heart icon"></i>
Это интересный момент, его нужно исследовать. Сомневаюсь, что заинлайнить получится. Спасибо, что заметил!

2018-04-24 16:59 UTC, indeyets requested changes
There's a bunch of inline comments.

Additionally:
1. please rebase
2. unit-tests are needed. at least for model stuff (list of subscribers, etc.)

2018-04-24 16:59 UTC, indeyets commented on package.json
> +    "classnames": "^2.2.5",
we always use `~`, not `^`. this is related to other dependencies introduced by this PR too

2018-04-24 16:59 UTC, indeyets commented on migrations/20180306184639_sent_emails_log.js
> +}
This `down` implementation is not correct, as it will transform logs of other types into notifications. Other types should be removed explicitly

2018-04-24 16:59 UTC, indeyets commented on app/mailers/BestOfDigestMailer.js
> +import { promisifyAll } from 'bluebird'
missed `;`
it is a requirement for all new files

2018-04-24 16:59 UTC, indeyets commented on app/views/emails/best-of-digest/Feed.jsx
> +};
missed newline

2018-04-24 16:59 UTC, indeyets commented on app/views/emails/best-of-digest/SummaryEmail.jsx
> +export const renderToString = (props) => ReactDOMServer.renderToStaticMarkup(SummaryEmail(props));
this line should be moved out of component's file. it should happen outside of `views`

2018-05-08 16:37 UTC, merged