Add startup messages
FreeFeed/freefeed-server pull request #521
Opened 2021-04-01 16:37 UTC by n1313

See https://freefeed.slack.com/archives/C0457L46F/p1617224191108700

<img width="664" alt="Screenshot 2021-04-02 at 00 35 24" src="https://user-images.githubusercontent.com/632081/113325904-936a9c80-934b-11eb-8c50-88cc08248d25.png">

2021-04-01 18:44 UTC, davidmz requested changes
Мы в/на сервере используем библиотеку debug для логирования. Собственно, чуть ниже твоих правок она объявляет логгер и пишет в него практически то же самое. Другое дело, что по умолчанию эти сообщения не показываются. Но это легко исправить, см. https://github.com/FreeFeed/freefeed-server/blob/stable/app/setup/environment.js#L14 — тут объявляются debug-имена, которые всегда показываются. Всё что нужно, это добавить в этот список 'freefeed:init'

2021-04-02 03:58 UTC, n1313 commented
> Мы в/на сервере используем библиотеку debug для логирования. 

Я заметил ее использование и немножко полистал документацию, но решил, что она предназначена для отладки, а не для вывода статусных сообщений. Исправлю. Спасибо!

2021-04-02 04:10 UTC, n1313 commented
Исправил.

<img width="565" alt="Screenshot 2021-04-02 at 12 08 57" src="https://user-images.githubusercontent.com/632081/113379542-65697480-93ac-11eb-8e8a-1916cc38d066.png">

2021-04-02 06:23 UTC, davidmz approved these changes

2021-04-02 06:23 UTC, merged