Add a bunch of new search operators
FreeFeed/freefeed-server pull request #674
Opened 2024-08-11 14:44 UTC by davidmz

### Added
- New search operators:
  - `clicked-by:`
  - `has:`
  - `comments:`
  - `likes:`
  - `clikes:`
  - `date:`
  - `post-date:`

  See [app/support/search/query-syntax.md](app/support/search/query-syntax.md) for details.

We need to run the bin/reindex_counters.js script after the database migration.

2024-08-16 11:06 UTC, indeyets requested changes
огромная работа 👍
немного переживаю, что `support/DbAdapter/search.js` / `utils.js` не покрыты типами.

2024-08-16 11:06 UTC, indeyets commented on app/support/search/query-syntax.md
> +* clicked-by:
```suggestion
* cliked-by:
```

2024-08-16 11:06 UTC, indeyets commented on CHANGELOG.md
> +  - `clicked-by:`
```suggestion
  - `cliked-by:`
```

2024-08-16 11:06 UTC, indeyets commented on app/support/search/query-syntax.md
> +**clicked-by:user1,user2** limits search to comments licked by user1 or user2.
```suggestion
**cliked-by:user1,user2** limits search to comments liked by user1 or user2.
```

2024-08-16 11:06 UTC, indeyets commented on app/support/search/query-syntax.md
> +`cat clicked-by:alice` will find all comments liked by Alice with the "cat" word.
```suggestion
`cat cliked-by:alice` will find all comments liked by Alice with the "cat" word.
```

2024-08-16 11:06 UTC, indeyets commented on app/support/search/query-syntax.md
> +Since `clicked-by:` makes sense only for comments, it switches the search scope to comments. So the query `cat clicked-by:alice` is equal to `in-comments: cat clicked-by:alice`. Being used in post bo
```suggestion
Since `cliked-by:` makes sense only for comments, it switches the search scope to comments. So the query `cat cliked-by:alice` is equal to `in-comments: cat cliked-by:alice`. Being used in post body scope (like `in-body: cliked-by:...`), `cliked-by:` is ignored.
```

2024-08-16 11:06 UTC, indeyets commented on app/support/search/date-parser.ts
> +export function parseDateExpression(dateExpr: string): [string, string] | null {
Есть смысл ввести отдельный тип `DateString` и возвращать кортеж этих типов. Хотя бы

```js
type DateString = `${number}-${number}-${number}` & { __brand: 'date' };
```

расписывать детальнее смысла нет, т.к. получится нечитаемо, да и branding всё равно даёт достаточно защиты

2024-08-16 11:06 UTC, indeyets commented on test/integration/support/DbAdapter/search-dates.js
> +      // Every post has 3 comments created ath the same day, day after and day after that:
```suggestion
      // Every post has 3 comments created on the same day, day after and day after that:
```

2024-08-19 06:45 UTC, davidmz commented on CHANGELOG.md
> +  - `clicked-by:`
Судя по количеству моих собственных опечаток, надо принимать от пользователя оба варианта:)

2024-08-23 09:30 UTC, indeyets approved these changes

2024-08-23 09:30 UTC, merged